/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizador_imagens;

import br.com.jmary.home.Home;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class Visualizador_Interno extends javax.swing.JPanel {

    int quantidade_de_arquivos_ajuda       = 2;    
    Class Classe;
    int img_Atual = 1;    
        
    Home Home;
    /**
     * Creates new form Visualizador_Interno2
     * @param Home2
     * @param img_Atual2
     * @param quantidade_de_arquivos_ajuda2
     * @param Classe2
     */
    public Visualizador_Interno( Home Home2, int img_Atual2 ,int quantidade_de_arquivos_ajuda2, Class Classe2 ) {
        initComponents();
        
        Home = Home2;
        img_Atual = img_Atual2;
        quantidade_de_arquivos_ajuda = quantidade_de_arquivos_ajuda2;
        Classe = Classe2;
        
        setarImagemInterna(img_Atual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbConteudo_Online = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/laranja_home.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 7);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/laranja_proximo.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/laranja_anterior.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel3, gridBagConstraints);

        lbConteudo_Online.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbConteudo_Online.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbConteudo_Online.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/anao.gif"))); // NOI18N
        lbConteudo_Online.setToolTipText("");

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(204, 0, 51));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Imagem");
        lbTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(lbConteudo_Online, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbConteudo_Online)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitulo))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        img_Atual=1;
        setarImagemInterna(img_Atual);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        img_Atual++;
        setarImagemInterna(img_Atual);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        img_Atual--;
        setarImagemInterna(img_Atual);
    }//GEN-LAST:event_jLabel3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbConteudo_Online;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
        
    private void setarImagemInterna( int img_Atual2 ){ 
        img_Atual = img_Atual2;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
                if( (img_Atual > 0) && (img_Atual <= quantidade_de_arquivos_ajuda) ){
                    
                    String arquivo_img = String.format ("%03d", img_Atual);
                    //System.out.println("arquivo_img: "+arquivo_img);
                
                    BufferedImage bufImg = null;
                    try{
                        InputStream is1 = Classe.getResourceAsStream( arquivo_img + ".jpg" );
                        bufImg = ImageIO.read( is1 );                        
                    }catch(Exception e){
                        
                        try {  
                            InputStream is2 = Classe.getResourceAsStream( arquivo_img + ".png" );
                            bufImg = ImageIO.read( is2 );
                        } catch (Exception ex) {}
                    }
                    
                    ImageIcon     icon   = null;
                    Image         image  = null;
                    try{                        
                        icon   = new ImageIcon(bufImg);
                        image  = icon.getImage();//ImageIO.read(f);  
                    } catch (Exception ex) {} 

                    try {  
                        image = icon.getImage();//ImageIO.read(f);  
                        int widith = image.getWidth(icon.getImageObserver() );
                        int height = image.getHeight(icon.getImageObserver() );
                                                                        
                        lbConteudo_Online.setIcon(new ImageIcon(image.getScaledInstance(
                            widith, height, Image.SCALE_DEFAULT)));

                    }catch(Exception ex){}
                
                    lbTitulo.setText( arquivo_img );
                }
                else{    
                    if( img_Atual <= 0){
                        img_Atual = quantidade_de_arquivos_ajuda;
                    }
                    else{
                        img_Atual = 1;
                    }
                    
                    String arquivo_img = String.format ("%03d", img_Atual);
                    //System.out.println("arquivo_img: "+arquivo_img);
                
                    BufferedImage bufImg = null;
                    try{
                        InputStream is1 = Classe.getResourceAsStream( arquivo_img + ".jpg" );
                        bufImg = ImageIO.read( is1 );                        
                    }catch(Exception e){
                        
                        try {  
                            InputStream is2 = Classe.getResourceAsStream( arquivo_img + ".png" );
                            bufImg = ImageIO.read( is2 );
                        } catch (IOException ex) {}
                    }
                    
                    ImageIcon     icon   = null;
                    Image         image  = null;
                    try{                        
                        icon   = new ImageIcon(bufImg);
                        image  = icon.getImage();//ImageIO.read(f);  
                    } catch (Exception ex) {} 

                    try {  
                        image = icon.getImage();//ImageIO.read(f);  
                        int widith = image.getWidth(icon.getImageObserver() );
                        int height = image.getHeight(icon.getImageObserver() );
                                                                        
                        lbConteudo_Online.setIcon(new ImageIcon(image.getScaledInstance(
                            widith, height, Image.SCALE_DEFAULT)));

                    }catch(Exception ex){}
                
                    lbTitulo.setText( arquivo_img );
                }
            
        } catch( InterruptedException e ){ } } }.start();
    }
}
